admin_item:
    pattern:  /{page}/{lang}
    defaults: { _controller: "SMAdminBundle:Item:index", page : 1, lang : null }
    requirements:
        page:  \d+
        lang:  \d+

admin_item_show:
    pattern:  /{id}/show
    defaults: { _controller: "SMAdminBundle:Item:show" }

admin_item_new:
    pattern:  /new
    defaults: { _controller: "SMAdminBundle:Item:new" }

admin_item_create:
    pattern:  /create
    defaults: { _controller: "SMAdminBundle:Item:create" }
    requirements: { _method: post }

admin_item_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SMAdminBundle:Item:edit" }

admin_item_update:
    pattern:  /{id}/update
    defaults: { _controller: "SMAdminBundle:Item:update" }
    requirements: { _method: post }

admin_item_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SMAdminBundle:Item:delete" }
    requirements: { _method: post|get }

admin_item_delete_all:
    pattern:  /deleteall
    defaults: { _controller: "SMAdminBundle:Item:deleteAll" }
    requirements: { _method: post }