<?php

namespace SM\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;
use SM\Bundle\AdminBundle\Entity\Counter;

/**
 * CounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CounterRepository extends EntityRepository
{
    /**
     * Find counter by ip
     * 
     * @param type $ip
     * @return type
     */
    public function findByIp($ip) {
        $rst = null;
        if (!empty($ip)) {
            $rst = $this->findBy(array('ip' => $ip), array('id' => 'DESC'));
            if (!empty($rst[0])) {
                return $rst[0];
            }
        }

        return $rst;
    }
    
    /**
     * adding new record
     * 
     * @param array $data
     * @return boolean
     */
    public function create($data)
    {
        $entCounter = new Counter();
        $entCounter->setIp($data['ip']);
        $entCounter->setTime($data['time']);
        $entCounter->setdate($data['date']);
        $em = $this->getEntityManager();
        $em->persist($entCounter);
        $em->flush();
        if ($em->getUnitOfWork()->getEntityState($entCounter) == UnitOfWork::STATE_NEW) {
            return $entCounter->getId();
        }
        
        return false;
    }
}
