<?php

namespace SM\Bundle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\UnitOfWork;

/**
 * GroupsLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemLanguageRepository extends EntityRepository
{

    /**
     * @param type $criteria criteria
     *
     * @return type
     */
    public function getTotal($criteria = array())
    {
        $rst = $this->findBy($criteria);

        return count($rst);
    }

    /**
     * @param type $productId productId
     *
     * @return type
     */
    public function findByItemId($id)
    {
        $rst = array();
        if (!empty($id)) {
            $rst = $this->findBy(array('item' => $id));
        }

        return $rst;
    }

    /**
     * @param type $productId productId
     *
     * @return type
     */
    public function findByItemIdAndLang($id, $lang)
    {
        $rst = null;
        if (!empty($id)) {
            $rst = $this->findBy(array('item' => $id, 'language' => $lang));
            if (!empty($rst[0])) {
                $rst = $rst[0];
            }
        }

        return $rst;
    }

    /**
     * Delete language by array id
     *
     * @param array $ids
     *
     * @return array
     */
    public function deleteByIds($ids = array())
    {
        $em = $this->getEntityManager();
        $rep = $em->getRepository('SMAdminBundle:Item');

        $rst = array();

        if (is_array($ids) && count($ids)) {
            foreach ($ids as $id) {
                $entity = $this->find($id);
                if ($entity instanceof \SM\Bundle\AdminBundle\Entity\ItemLanguage) {
                    $catId = $entity->getItem()->getId();
                    $em->remove($entity);
                    //Get all product language by idComtype
                    //If to have 1 item we need to delete product too
                    //else we need delete product language
                    $lstItemLangs = $this->findByItemId($catId);
                    if (count($lstItemLangs) == 1) {
                        if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                            $rst[] = $id;
                        }
                        $em->persist($entity);
                        //delete product too
                        $em->flush();
                        //delete product language
                        $rep->deleteByIds(array($catId));
                    } else {
                        if ($em->getUnitOfWork()->getEntityState($entity) == UnitOfWork::STATE_REMOVED) {
                            $rst[] = $id;
                        }
                        //Onlye delete article language
                        $em->flush();
                    }
                }
            }
        }

        return $rst;
    }

    /**
     *
     * @param type $langId
     * @param type $name
     * @param type $itemTypeId
     * @param type $limit
     * @param type $offset
     * @param type $criteria
     * @param type $orders
     * @return array 
     */
    public function findByLangAndNameAndItemType($langId, $name = '', $itemTypeId = '', $limit = null, $offset = null, $criteria = array(), $orders = array())
    {
        $rst = array();
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('il');

            $qb->select('il, i')
                    ->join('il.item', 'i')
                    ->join('i.itemtype', 'it')
                    ->where('il.language=:langId');

            if (!empty($limit)) {
                $qb->setMaxResults($limit);
            }

            if (!empty($offset)) {
                $qb->setFirstResult($offset);
            }

            if (!empty($itemTypeId)) {
                $qb->andWhere('i.itemtype=:itemTypeId');
                $qb->setParameter('itemTypeId', $itemTypeId);
            }

            if (!empty($name)) {
                $qb->andWhere('il.name LIKE ?1');
                $qb->andWhere('il.price LIKE ?2');
                $qb->andWhere('il.description LIKE ?3');
                $qb->setParameter(1, "%$name%");
                $qb->setParameter(2, "%$name%");
                $qb->setParameter(3, "%$name%");
            }

            if (is_array($criteria) && count($criteria) > 0) {
                foreach ($criteria as $key => $cri) {
                    $qb->andWhere("i." . $cri['fieldName'] . " " . $cri['op'] . " " . " ?$key");

                    if ($cri['op'] == 'LIKE') {
                        $qb->setParameter($key, "%" . $cri['fieldValue'] . "%");
                    } else {
                        $qb->setParameter($key, $cri['fieldValue']);
                    }
                }
            }

            $qb->setParameter('langId', $langId);

            if (!empty($orders)) {
                $qb->orderBy($orders);
            } else if (is_array($orders) && count($orders) > 0) {
                foreach ($orders as $k => $v) {
                    $qb->orderBy($k, $v);
                }
            } else {
                $qb->orderBy('il.name', 'ASC');
            }

            //echo $qb->getQuery()->getSQL();die;
            return $qb->getQuery()->getResult();
        }

        return $rst;
    }

    /**
     *
     * @param type $langId
     * @param type $name
     * @param type $itemTypeId
     * @param type $criteria
     * @return type 
     */
    public function getTotalByLangAndNameAndItemType($langId, $name = '', $itemTypeId = '', $criteria = array())
    {
        if (!empty($langId)) {
            $qb = $this->createQueryBuilder('il');

            $qb->select('il, i')
                    ->join('il.item', 'i')
                    ->join('i.itemtype', 'it')
                    ->where('il.language=:langId');

            if (!empty($itemTypeId)) {
                $qb->andWhere('i.itemtype=:itemTypeId');
                $qb->setParameter('itemTypeId', $itemTypeId);
            }

            if (!empty($name)) {
                $qb->andWhere('il.name LIKE ?1');
                $qb->andWhere('il.price LIKE ?2');
                $qb->andWhere('il.description LIKE ?3');
                $qb->setParameter(1, "%$name%");
                $qb->setParameter(2, "%$name%");
                $qb->setParameter(3, "%$name%");
            }

            if (is_array($criteria) && count($criteria) > 0) {
                foreach ($criteria as $key => $cri) {
                    $qb->andWhere("i." . $cri['fieldName'] . " " . $cri['op'] . " " . " ?$key");

                    if ($cri['op'] == 'LIKE') {
                        $qb->setParameter($key, "%" . $cri['fieldValue'] . "%");
                    } else {
                        $qb->setParameter($key, $cri['fieldValue']);
                    }
                }
            }

            $qb->setParameter('langId', $langId);
            //echo $qb->getQuery()->getSQL();die;
            return count($qb->getQuery()->getResult());
        }
        return 0;
    }

}
