<?php

namespace SM\Bundle\FrontBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ItemController__JMSInjector
{
    public static function inject($container) {
        $instance = new \SM\Bundle\FrontBundle\Controller\ItemController();
        return $instance;
    }
}
